# 快速开始

# - 增加 CI 配置文件：
# 1. 在项目根目录中增加 .coding-ci.yml 配置文件。
# 2. 其描述了当仓库发生一些事件时，Coding-CI 应该如何去进行处理。
# 3. 将配置文件 push 到远程 master

# 想了解配置文件更多用法请移步 【配置文件】（https://ci.coding.net/docs/configuration.html）

master:
  push:
    - stages:
      - name: Install Pnpm
        script: npm i -g pnpm
      - name: Install Packages
        script: pnpm i
      - name: Build
        script: pnpm run build
